"""Linked-reward calibration: the estimator used for both the simulation and the application.

The observed data are replayed excursions and a recorded annunciation log. Linking the two makes the
reward of an excursion observed for *every* excursion, including excursions with no alarm assigned under the linkage convention, whose
linked seconds are observed zero rather than missing. Write

    Y_ij  = total linked annunciation seconds of excursion j of patient i   (Y = 0 when unlinked),
    a_0   = E(Y | D = d, Z = z)                                            at the limit in force,
    B_m(u) = int a_0(d, z) nu_u(dd, dz)                                    the linked burden under u,

where nu_u is the excursion mean measure generated by limit u. `a_0` is identified at the limit in
force; `B_m(u)` for a candidate limit u is identified under the transport and support conditions the
manuscript states.

Estimation is by cells. The cell map partitions duration (and optionally a feature such as overshoot)
into finitely many cells fixed before estimation. Each cell carries its own **carrier**:

    short cells   a nominal duration bin, carrier R = excursion count,
                  so beta_c = E(S_ic) / E(R_ic) is linked seconds per excursion (units s);
    pooled cells  a range of durations per cell, carrier R = replayed duration seconds,
                  so beta_c = E(S_ic) / E(R_ic) is the annunciation ratio (dimensionless).

For every cell, `beta_c * R_c(u)` is in seconds, so the standardized burden

    Bhat_m(u) = sum_c beta_c R_c(u)

is a sum of linked seconds whatever the carrier. Its fixed-map target is the cell-standardised
functional, which equals the scientific transported burden only under the stated within-cell
and coarsening conditions. This is the generic-carrier form: a single smooth
functional of patient-level sums, which is what makes the delta method and the patient-cluster
bootstrap apply to the estimator that is actually computed.

Everything here operates on arrays already summed within a patient, so a bootstrap replicate is a
resample of patient rows followed by a sum: `estimate(...)` is the same function of the patient means
in every replicate.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict

import numpy as np

__all__ = [
    "CellMap",
    "COUNT",
    "SECONDS",
    "reward_rates",
    "standardized_burden",
    "replayed_burden",
    "burden_contrast",
    "kappa",
    "percent_change",
    "feature_support_map",
    "support_diagnostics",
    "joint_carrier",
    "joint_target_seconds",
    "joint_support_diagnostics",
    "fallback_diagnostics",
    "plateau_ratio",
    "PLATEAU_FROM_INDEX",
    "cluster_bootstrap",
]

COUNT = "count"
SECONDS = "seconds"

#: First cell of the high-duration plateau: index 30 is 60 s on the 2-second exact grid.
PLATEAU_FROM_INDEX = 30


# ----------------------------------------------------------------------------------- the cell map
@dataclass(frozen=True)
class CellMap:
    """A fixed partition of duration into exact cells and pooled tail cells.

    `width` is the grid spacing of the exact cells, `n_exact` their number, and `tail_edges` the left
    edges of the pooled cells above them. The map must be fixed before estimation: `beta` and the
    target carriers are both indexed by it, and the asymptotic argument treats it as deterministic.
    """

    width: float = 2.0
    n_exact: int = 60
    tail_edges: tuple = (120.0, 180.0, 300.0, 600.0)
    tail_midpoints: tuple = (150.0, 240.0, 450.0, 900.0)

    @property
    def n_tail(self) -> int:
        return len(self.tail_edges)

    @property
    def n_cells(self) -> int:
        return self.n_exact + self.n_tail

    @property
    def carrier(self) -> np.ndarray:
        """Carrier kind of every cell: counts in exact cells, seconds in pooled tail cells."""
        return np.array([COUNT] * self.n_exact + [SECONDS] * self.n_tail, dtype=object)

    @property
    def is_exact(self) -> np.ndarray:
        m = np.zeros(self.n_cells, dtype=bool)
        m[: self.n_exact] = True
        return m

    @property
    def representative_duration(self) -> np.ndarray:
        """Duration value of each exact cell, and the nominal midpoint of each pooled cell."""
        return np.array([self.width * i for i in range(self.n_exact)] + list(self.tail_midpoints),
                        dtype=float)

    def index(self, d) -> np.ndarray:
        """Cell index of each duration. Durations at or above the last tail edge fall in the last cell."""
        d = np.asarray(d, dtype=float)
        idx = np.where(d < self.n_exact * self.width,
                       np.floor(d / self.width),
                       self.n_exact + np.searchsorted(np.asarray(self.tail_edges), d, side="right") - 1)
        return np.clip(idx, 0, self.n_cells - 1).astype(int)

    def to_json(self, path) -> None:
        with open(path, "w") as f:
            json.dump(asdict(self), f, indent=1)

    @classmethod
    def from_json(cls, path) -> "CellMap":
        with open(path) as f:
            d = json.load(f)
        return cls(width=float(d["width"]), n_exact=int(d["n_exact"]),
                   tail_edges=tuple(d["tail_edges"]), tail_midpoints=tuple(d["tail_midpoints"]))


# ------------------------------------------------------------------------------- the reward rates
def reward_rates(linked_seconds, carrier_totals, fallback=None):
    """beta_c = sum_i S_ic / sum_i R_ic, cell by cell.

    `linked_seconds` and `carrier_totals` are already summed over the patients in the sample (or in
    the bootstrap replicate). A cell with no carrier mass has no estimate: it takes `fallback` if one
    is supplied (broadcast over any trailing feature axis) and zero otherwise. Returning zero for an
    unobserved cell is deliberate — it contributes no linked seconds, and `support_diagnostics`
    reports how much target mass falls in such cells rather than letting it pass silently.
    """
    S = np.asarray(linked_seconds, dtype=float)
    R = np.asarray(carrier_totals, dtype=float)
    if S.shape != R.shape:
        raise ValueError(f"linked seconds {S.shape} and carriers {R.shape} must have the same shape")
    have = R > 0
    beta = np.divide(S, np.where(have, R, 1.0), out=np.zeros_like(S), where=have)
    if fallback is not None:
        fb = np.asarray(fallback, dtype=float)
        if fb.ndim == S.ndim - 1:
            fb = fb[..., None]
        beta = np.where(have, beta, np.broadcast_to(fb, beta.shape))
    return beta


def standardized_burden(beta, carrier_target):
    """Bhat_m(u) = sum_c beta_c R_c(u): linked seconds under the target policy's excursion measure."""
    beta = np.asarray(beta, dtype=float)
    R = np.asarray(carrier_target, dtype=float)
    if beta.shape != R.shape:
        raise ValueError(f"beta {beta.shape} and target carriers {R.shape} must have the same shape")
    return float((beta * R).sum())


def replayed_burden(cellmap, counts, tail_seconds):
    """Replayed excursion seconds: exact cells contribute count x duration, pooled cells their seconds."""
    counts = np.asarray(counts, dtype=float)
    tail_seconds = np.asarray(tail_seconds, dtype=float)
    d = cellmap.representative_duration[: cellmap.n_exact]
    return float(counts[: cellmap.n_exact] @ d + tail_seconds.sum())


def burden_contrast(b_target, b_base):
    """Percentage change in linked burden from the limit in force to the candidate limit.

    Positive means the candidate limit produces less linked burden.
    """
    if b_base == 0:
        return float("nan")
    return 100.0 * (1.0 - b_target / b_base)


def kappa(b_base, b_target, rep_base, rep_target):
    """Replay bias factor: the ratio by which the replayed relative burden misstates the corrected one.

    kappa = (Bm(u0)/Bhat(u0)) / (Bm(u1)/Bhat(u1)). Returns nan on a zero denominator rather than
    raising, so a bootstrap replicate that loses a cell does not abort the run.
    """
    with np.errstate(divide="ignore", invalid="ignore"):
        r0 = b_base / rep_base if rep_base else float("nan")
        r1 = b_target / rep_target if rep_target else float("nan")
        return float(r0 / r1) if r1 else float("nan")


# ------------------------------------------------------------- the high-duration plateau, one way
def plateau_ratio(linked, total, from_index=PLATEAU_FROM_INDEX):
    """Pooled ratio over the cells at or above `from_index`, THE POOLED TAIL CELLS INCLUDED.

    `linked` and `total` are two quantities indexed by the same full cell map -- the exact cells
    first, then the pooled tail cells -- already summed over the sample. The plateau is the ratio of
    their sums from `from_index` to the end of the map, so every cell is weighted by the mass it
    actually holds rather than counted once.

    The pooled tail cells are included because the plateau is a statement about excursions of at
    least `from_index` cells' duration, and the tail cells hold nothing else: every excursion in them
    is longer than every excursion in the exact cells above the cut. Dropping them would silently
    restrict the estimand to durations under the first tail edge while still describing it as "at or
    above 60 s", and would weight the longest excursions -- the ones that dominate the burden -- at
    zero. One definition, used at every site, is what keeps the reported plateau from forking.

    Two quantities are computed this way and are meant to be compared on the same slice: the linkage
    probability (annunciated excursions over excursions) and the annunciation ratio (linked seconds
    over replayed seconds). Returns nan when the slice carries no mass at all.
    """
    a = np.asarray(linked, dtype=float)[from_index:]
    b = np.asarray(total, dtype=float)[from_index:]
    den = float(np.nansum(b))
    if not den > 0:
        return float("nan")
    return float(np.nansum(a) / den)


# ------------------------------------------------------------------------------ the feature map
def feature_support_map(counts_by_cell_feature, nmin=5):
    """Which (cell, feature) cells carry their own reward, and which fall back to the duration reward.

    The map is a deterministic function of the counts it is given. Pass the counts of an independent
    split to prespecify it; pass the analysis sample's own counts only as the in-sample sensitivity,
    and hold the result fixed across bootstrap replicates either way.
    """
    n = np.asarray(counts_by_cell_feature, dtype=float)
    return n >= float(nmin)


def support_diagnostics(cellmap, baseline_counts, target_counts, target_tail_seconds,
                        min_for_precision=20):
    """Support of the target policy's replayed seconds on the DURATION cells (the duration marginal).

    Every quantity here is indexed by the duration marginal of the cell map, so it answers "is this
    duration represented in the baseline sample", not "is this (duration, feature) combination
    represented". The duration-by-feature estimand integrates over the joint measure and its support
    condition belongs on joint cells: `joint_support_diagnostics` computes that one, and the two are
    reported side by side because a target can be fully supported on duration cells and unsupported
    on the joint cells the estimator actually uses.

    `unsupported` is the identification problem: target mass in duration cells with no baseline
    excursion at all, where no reward is identified. `imprecise` is the separate practical rule that a
    duration cell with fewer than `min_for_precision` baseline excursions gives a noisy rate; it
    restricts precision, not identification, and the two are reported separately on purpose.
    `supported_precise` is its complement, the share carried by duration cells at or above the
    precision floor.
    """
    nb = np.asarray(baseline_counts, dtype=float)
    nt = np.asarray(target_counts, dtype=float)
    ts = np.asarray(target_tail_seconds, dtype=float)
    ne = cellmap.n_exact
    d = cellmap.representative_duration[:ne]
    total = float(nt[:ne] @ d + ts.sum())
    if not total > 0:
        return {"replayed_seconds": 0.0, "share_unsupported": float("nan"),
                "share_imprecise": float("nan"), "share_supported_precise": float("nan"),
                "share_pooled_tail": float("nan"), "share_last_pooled_cell": float("nan"),
                "n_last_pooled_cell": 0.0, "baseline_n_last_pooled_cell": 0.0}
    empty = nb == 0
    thin = nb < float(min_for_precision)
    thick = nb >= float(min_for_precision)

    def share(mask):
        return float(((nt[:ne] * mask[:ne]) @ d + ts[mask[ne:]].sum()) / total)

    return {
        "replayed_seconds": total,
        "share_unsupported": share(empty),
        "share_imprecise": share(thin),
        "share_supported_precise": share(thick),
        "share_pooled_tail": float(ts.sum() / total),
        "share_last_pooled_cell": float(ts[-1] / total) if ts.size else float("nan"),
        "n_last_pooled_cell": float(nt[cellmap.n_cells - 1]),
        "baseline_n_last_pooled_cell": float(nb[cellmap.n_cells - 1]),
    }


# ------------------------------------------------- the joint (duration x feature) cells the estimand uses
def joint_carrier(cellmap, joint_counts, joint_seconds):
    """Carrier of every joint cell: excursion counts in the exact cells, replayed seconds in the pooled ones.

    Both inputs are ``(n_cells, n_feature_bins)``. This is the generic-carrier convention of the module
    lifted to the joint map, so ``beta * joint_carrier(...)`` is in linked seconds cell by cell.
    """
    n = np.asarray(joint_counts, dtype=float)
    s = np.asarray(joint_seconds, dtype=float)
    if n.shape != s.shape:
        raise ValueError(f"joint counts {n.shape} and seconds {s.shape} must have the same shape")
    ne = cellmap.n_exact
    out = np.empty_like(n)
    out[:ne] = n[:ne]
    out[ne:] = s[ne:]
    return out


def joint_target_seconds(cellmap, joint_counts, joint_seconds):
    """Replayed seconds held by every joint cell: count x the exact cell's one duration, or the pooled seconds."""
    n = np.asarray(joint_counts, dtype=float)
    s = np.asarray(joint_seconds, dtype=float)
    if n.shape != s.shape:
        raise ValueError(f"joint counts {n.shape} and seconds {s.shape} must have the same shape")
    ne = cellmap.n_exact
    out = np.empty_like(n)
    out[:ne] = n[:ne] * cellmap.representative_duration[:ne, None]
    out[ne:] = s[ne:]
    return out


def joint_support_diagnostics(cellmap, baseline_joint_counts, target_joint_counts,
                              target_joint_seconds, nmin=5):
    """Support of the target measure on the JOINT (duration, feature) cells, not the duration marginal.

    The duration-by-feature estimand is an integral of a_0(d, z) against the target's joint excursion
    measure, so the support condition is a statement about joint cells: a joint cell holding target
    seconds and no baseline excursion identifies no reward there, whatever the duration marginal says.
    `share_unsupported_joint` is that share of the target's replayed seconds; `share_sparse_joint` is
    the separate share in joint cells holding between one and `nmin - 1` baseline excursions, which
    are identified but estimated off very little data and are exactly the cells the fallback rule
    hands to the duration-only rate.
    """
    nb = np.asarray(baseline_joint_counts, dtype=float)
    w = joint_target_seconds(cellmap, target_joint_counts, target_joint_seconds)
    if nb.shape != w.shape:
        raise ValueError(f"baseline joint counts {nb.shape} and target {w.shape} must have the same shape")
    total = float(w.sum())
    if not total > 0:
        return {"replayed_seconds_joint": 0.0, "share_unsupported_joint": float("nan"),
                "share_sparse_joint": float("nan")}
    return {
        "replayed_seconds_joint": total,
        "share_unsupported_joint": float(w[nb == 0].sum() / total),
        "share_sparse_joint": float(w[(nb > 0) & (nb < float(nmin))].sum() / total),
    }


def fallback_diagnostics(cellmap, uses_own_rate, beta, target_joint_counts, target_joint_seconds):
    """How much of the target the duration-only fallback carries, in seconds and in linked burden.

    `uses_own_rate` is the boolean joint map of cells that estimate their own duration-by-feature
    reward; every other joint cell takes the duration-only rate instead. A count of such cells says
    nothing about their weight, so both shares here are burdens: `share_target_seconds_fallback` is
    the share of the candidate's replayed seconds routed through the coarse rate, and
    `share_linked_burden_fallback` the share of the standardized linked seconds those cells
    contribute. `beta` is the reward per carrier unit already in force in each joint cell (the own
    rate inside the map, the duration-only rate outside it).
    """
    fb = ~np.asarray(uses_own_rate, dtype=bool)
    secs = joint_target_seconds(cellmap, target_joint_counts, target_joint_seconds)
    contrib = np.asarray(beta, dtype=float) * joint_carrier(cellmap, target_joint_counts,
                                                            target_joint_seconds)
    if fb.shape != secs.shape:
        raise ValueError(f"fallback map {fb.shape} and target {secs.shape} must have the same shape")
    tot_s = float(secs.sum())
    tot_b = float(contrib.sum())
    return {
        "share_target_seconds_fallback": float(secs[fb].sum() / tot_s) if tot_s > 0 else float("nan"),
        "share_linked_burden_fallback": float(contrib[fb].sum() / tot_b) if tot_b != 0 else float("nan"),
        "n_cells_fallback": int(fb.sum()),
    }


# --------------------------------------------------------------------------- clustered resampling
def cluster_bootstrap(n_patients, statistic, n_replicates=400, seed=20260902):
    """Resample patients with replacement and recompute `statistic` on the resampled index.

    `statistic` takes an index array of patient rows and returns a dict of floats. Patients are the
    independent unit: admissions and excursions move with the patient, and the cell map is passed in
    from outside so that it does not move with the replicate.
    """
    rng = np.random.default_rng(seed)
    draws = {}
    for _ in range(int(n_replicates)):
        idx = rng.integers(0, n_patients, n_patients)
        for k, v in statistic(idx).items():
            draws.setdefault(k, []).append(v)
    return {k: np.asarray(v, dtype=float) for k, v in draws.items()}


def percentile_ci(draws, lo=2.5, hi=97.5, min_finite=20):
    """Percentile interval of each bootstrap draw array, nan when too few replicates are finite."""
    out = {}
    for k, v in draws.items():
        v = np.asarray(v, dtype=float)
        if np.isfinite(v).sum() >= min_finite:
            out[k] = [float(np.nanpercentile(v, lo)), float(np.nanpercentile(v, hi))]
        else:
            out[k] = [float("nan"), float("nan")]
    return out


# --------------------------------------------------------------- the estimator, end to end
@dataclass
class LinkedRewardFit:
    """Result of one linked-reward calibration on one sample."""

    beta_duration: np.ndarray
    beta_feature: np.ndarray | None
    burden: dict = field(default_factory=dict)
    replayed: dict = field(default_factory=dict)
    fallback_cells: int = 0
    empty_map_cells: int = 0


def estimate(cellmap, linked_seconds, carrier_totals, targets,
             linked_seconds_feature=None, carrier_totals_feature=None,
             targets_feature=None, feature_ok=None):
    """One linked-reward calibration.

    Parameters
    ----------
    cellmap
        The fixed `CellMap`.
    linked_seconds, carrier_totals
        Cell-indexed sums over the patients in the sample: linked seconds, and the carrier of each
        cell (excursion counts in exact cells, replayed seconds in pooled cells).
    targets
        ``{policy: carrier_target}``: the same carrier, by cell, under each candidate policy.
    linked_seconds_feature, carrier_totals_feature, targets_feature, feature_ok
        The duration-by-feature versions. `feature_ok` is the prespecified map from
        `feature_support_map`; cells outside it take the duration-only reward.

    Returns
    -------
    LinkedRewardFit with the reward rates and the standardized burden under each policy, under
    duration-only transport and, when the feature arrays are supplied, duration-by-feature transport.
    """
    beta1 = reward_rates(linked_seconds, carrier_totals)
    fit = LinkedRewardFit(beta_duration=beta1, beta_feature=None)
    fit.burden["duration"] = {u: standardized_burden(beta1, R) for u, R in targets.items()}

    if linked_seconds_feature is not None:
        ok = np.ones_like(np.asarray(carrier_totals_feature), dtype=bool) if feature_ok is None \
            else np.asarray(feature_ok, dtype=bool)
        R2 = np.asarray(carrier_totals_feature, dtype=float)
        have = ok & (R2 > 0)
        beta2 = reward_rates(linked_seconds_feature, np.where(have, R2, 0.0), fallback=beta1)
        fit.beta_feature = beta2
        fit.fallback_cells = int((~ok).sum())
        fit.empty_map_cells = int((ok & (R2 <= 0)).sum())
        fit.burden["feature"] = {u: standardized_burden(beta2, R) for u, R in targets_feature.items()}
    return fit
